#! /bin/bash

export SCRIPTPATH="$(cd "$(dirname "$0")" ; pwd -P)"
# clean cache from last run
if [ -f "/tmp/leftwm-theme-down" ]; then
   /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# sets resolution
feh --bg-scale $SCRIPTPATH/bg.jpg &
picom -cf &
mv -f $SCRIPTPATH/alacritty.yml ~/.config/alacritty &
conky -c $SCRIPTPATH/clock.conf
